/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package shoppingcart;

import java.math.BigDecimal;
import java.util.Scanner;

public class App {
    private static Inventory inventory;
    private static ShoppingCart shoppingCart;
    static Scanner sc = new Scanner(System.in);

    public static void main(String[] args) {
        inventory = new Inventory();
        addDefaultItems();
        shoppingCart = new ShoppingCart(inventory);
        displayWelcomePage();
        System.out.println("Enter your choice: ");
        int choice = Integer.parseInt(sc.nextLine());

        while (choice != 4) {
            if (choice == 1) {
                manageInventory(inventory);
            } else if (choice == 2) {
                manageSale(inventory);
            } else if (choice == 3) {
                viewShoppingCart();
            }
            displayWelcomePage();
            choice = Integer.parseInt(sc.nextLine());
            System.out.println("Enter your choice: ");
        }

        System.out.println("Thank you, Visit again!");
    }

    private static void addDefaultItems() {
        inventory.add(new Item("1", "java book", ItemType.BOOK, BigDecimal.valueOf(150)));
        inventory.add(new Item("2", "H&M BLACKS", ItemType.TSHIRT, BigDecimal.valueOf(1500)));
        inventory.add(new Item("3", "2023", ItemType.CALENDER, BigDecimal.valueOf(200)));
        inventory.add(new Item("4", "Ink pen", ItemType.PEN, BigDecimal.valueOf(50)));
    }

    private static void displayWelcomePage() {
        System.out.println("|| Welcome to Big-Bazaar inventory management ||");
        System.out.println("1. Inventory");
        System.out.println("2. Sell");
        System.out.println("3. View cart");
        System.out.println("4. Exit");
    }

    private static void manageInventory(Inventory inventory) {
        System.out.println();
        System.out.println("What actions do you want to perform. . .");
        System.out.println("1. Add item to inventory");
        System.out.println("2. Delete item from inventory");
        System.out.println("3. View inventory");
        System.out.println("Enter your choice");
        int choice = Integer.parseInt(sc.nextLine());
        if (choice == 1) {
            addItemsToInventory(inventory);
        } else if (choice == 2) {
            removeItemFromInventory(inventory);
        } else {
            viewInventory(inventory);
        }
    }

    private static void addItemsToInventory(Inventory inventory) {
        System.out.println();
        System.out.println("Enter item detail you want to add");
        System.out.println("Enter item ID");
        String id = sc.nextLine();

        System.out.println("Enter item Name");
        String name = sc.nextLine();

        System.out.println("Enter item Type");
        ItemType itemType = ItemType.valueOf(sc.nextLine().toUpperCase());

        System.out.println("Enter item Price");
        BigDecimal price = new BigDecimal(sc.nextLine());

        Item item = new Item(id, name, itemType, price);
        inventory.add(item);
    }

    private static void viewInventory(Inventory inventory) {
        System.out.println(inventory);
    }

    private static void removeItemFromInventory(Inventory inventory) {
        System.out.println();
        System.out.println("Enter item detail you want to delete");
        System.out.println("Enter item ID");
        String id = sc.nextLine();

        System.out.println("Enter item Name");
        String name = sc.nextLine();

        System.out.println("Enter item Type");
        ItemType itemType = ItemType.valueOf(sc.next().toUpperCase());

        System.out.println("Enter item Price");
        BigDecimal price = new BigDecimal(sc.nextLine());

        Item item = new Item(id, name, itemType, price);
        inventory.remove(item);
    }

    private static void manageSale(Inventory inventory) {
        System.out.println("Welcome to sales dept");
        System.out.println("1. Add items to cart");
        System.out.println("2. Remove items from cart");
        int num = Integer.parseInt(sc.nextLine());

        String itemId;
        int itemQuantity;
        if (num == 1) {
            System.out.println("Enter item ID you want to add to cart from inventory");
            itemId = sc.nextLine();
            System.out.println("Enter item quantity");
            itemQuantity=Integer.parseInt(sc.nextLine());
            addItemsToShoppingCart(inventory, itemId, itemQuantity);
        } else if (num == 2) {
            System.out.println("Enter item ID you want to remove from cart");
            itemId = sc.nextLine();
            removeItemsFromShoppingCart(inventory, itemId);
        } else {
            throw new IllegalArgumentException("Please press the right key");
        }

    }

    private static void addItemsToShoppingCart(Inventory inventory, String itemId, int itemQuantity) {

        boolean isItemPresent = inventory.isItemPresentInInventory(itemId);
        if (isItemPresent) {
            shoppingCart.addItem(new LineItem(itemId, itemQuantity));
        } else {
            throw new IllegalArgumentException("Item with given Id is not present in inventory");
        }
    }

    private static void removeItemsFromShoppingCart(Inventory inventory, String itemId) {
        boolean isItemPresent = inventory.isItemPresentInInventory(itemId);
        if (isItemPresent) {
            shoppingCart.removeItem(new LineItem(itemId));
        } else {
            throw new IllegalArgumentException("Item with given Id is not present in inventory");
        }
    }

    private static void viewShoppingCart() {
        System.out.println(shoppingCart);
    }


}
